version: '3'
services:
  mongodb:
    image: mvertes/alpine-mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    entrypoint:
      - elasticsearch
      - -Ehttp.port=9200
      - -Ehttp.cors.enabled=true
      - -Ehttp.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358,http://localhost:3000,https://opensource.appbase.io
      - -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - -Ehttp.cors.allow-credentials=true
    user: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  # elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:3.2.3
    ports:
     - "1358:1358"
    links:
      - elasticsearch

